# Generated by Django 4.1.3 on 2023-04-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
